(function(){
'use strict';
if(window.__TasneefSupervisorPortalAdminBridgeV10850)return;
window.__TasneefSupervisorPortalAdminBridgeV10850=true;
const BUILD='V10850-ADMIN-BRIDGE';
const $=id=>document.getElementById(id),S=v=>String(v??'').trim(),E=v=>S(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const token=()=>localStorage.getItem('tasneef_session_token_v10817')||localStorage.getItem('tasneef_permission_session_v10817')||'';
const state={tasks:[],supervisors:[],projects:[],channel:null,bc:null,requests:0};
const safeCall=(names,...args)=>{for(const n of names){const f=n.split('.').reduce((o,k)=>o?.[k],window);if(typeof f==='function'){try{return f(...args)}catch(e){console.warn(BUILD,n,e)}}}};
function notify(t,type='ok'){if(typeof window.msg==='function')window.msg(t,type);else console.info(BUILD,t)}
async function waitSb(){for(let i=0;i<100;i++){if(window.sb)return window.sb;await new Promise(r=>setTimeout(r,100))}throw new Error('Supabase غير جاهز')}
function ensurePage(){let page=$('adminTasks');if(!page){page=document.createElement('section');page.id='adminTasks';page.className='page hidden';document.querySelector('main')?.appendChild(page)}page.innerHTML=`
<div class="card"><div style="display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap"><div><h2>مهام المشرفين — Supervisor Portal Unified</h2><p class="muted">أي مهمة أو تحديث يظهر فورًا في نسخة المشرف والإدارة.</p></div><button class="light" id="spuAdminTaskRefresh">تحديث</button></div></div>
<div style="display:grid;grid-template-columns:minmax(300px,.7fr) minmax(420px,1.3fr);gap:12px" id="spuAdminTasksLayout">
 <div class="card"><h3>إضافة / تعديل مهمة</h3><input type="hidden" id="spuTaskId"><label>المشرف</label><select id="spuTaskSupervisor"></select><label>المشروع</label><select id="spuTaskProject"><option value="">بدون مشروع</option></select><label>العنوان</label><input id="spuTaskTitle"><label>الوصف</label><textarea id="spuTaskDescription"></textarea><div class="grid"><label>الأولوية</label><select id="spuTaskPriority"><option value="normal">عادية</option><option value="high">مهمة</option><option value="urgent">عاجلة</option></select><label>الموعد النهائي</label><input id="spuTaskDue" type="datetime-local"><label>ملاحظات الإدارة</label><textarea id="spuTaskAdminNotes"></textarea></div><div class="actions"><button id="spuTaskSave">حفظ المهمة</button><button class="light" id="spuTaskClear">تفريغ</button></div></div>
 <div class="card"><div style="display:grid;grid-template-columns:1fr 1fr auto;gap:8px"><select id="spuTaskFilterSupervisor"><option value="">كل المشرفين</option></select><select id="spuTaskFilterStatus"><option value="">كل الحالات</option><option value="new">جديدة</option><option value="in_progress">قيد التنفيذ</option><option value="completed">مكتملة</option><option value="overdue">متأخرة</option><option value="cancelled">ملغاة</option><option value="review">تحتاج مراجعة</option></select><button class="light" id="spuTaskFilterBtn">تطبيق</button></div><div id="spuAdminTaskState" style="padding:15px;text-align:center;color:#64766f">جاري التحميل…</div><div id="spuAdminTaskList"></div></div>
</div><style>@media(max-width:900px){#spuAdminTasksLayout{grid-template-columns:1fr!important}}</style>`;
bind();return page}
async function loadOptions(){const sb=await waitSb();state.requests+=2;const [u,p]=await Promise.all([sb.from('app_users').select('*').eq('is_active',true),sb.from('projects').select('id,name,is_active,status').eq('is_active',true)]);if(u.error)throw u.error;if(p.error)throw p.error;state.supervisors=(u.data||[]).filter(x=>S(x.role_key||x.role)==='supervisor');state.projects=(p.data||[]).filter(x=>!['stopped','inactive','archived'].includes(S(x.status).toLowerCase()));const sop=state.supervisors.map(x=>`<option value="${E(x.id)}">${E(x.full_name||x.name||x.username)}</option>`).join('');$('spuTaskSupervisor').innerHTML='<option value="">اختر المشرف</option>'+sop;$('spuTaskFilterSupervisor').innerHTML='<option value="">كل المشرفين</option>'+sop;$('spuTaskProject').innerHTML='<option value="">بدون مشروع</option>'+state.projects.map(x=>`<option value="${E(x.id)}">${E(x.name)}</option>`).join('')}
async function loadTasks(){const sb=await waitSb();$('spuAdminTaskState').textContent='جاري تحميل المهام…';state.requests++;const {data,error}=await sb.rpc('tasneef_admin_tasks_v10850',{p_session_token:token()||null,p_supervisor_id:$('spuTaskFilterSupervisor')?.value?Number($('spuTaskFilterSupervisor').value):null,p_status:$('spuTaskFilterStatus')?.value||null});if(error)throw error;if(data?.ok===false)throw new Error(data.message);state.tasks=data?.rows||[];$('spuAdminTaskState').textContent=state.tasks.length?`تم تحميل ${state.tasks.length} مهمة`:'لا توجد مهام';$('spuAdminTaskList').innerHTML=state.tasks.map(t=>`<article style="border:1px solid #d9e7e1;border-right:5px solid #075542;border-radius:14px;padding:11px;margin-top:9px"><div style="display:flex;justify-content:space-between;gap:8px"><b>${E(t.title)}</b><span>${E(t.status)}</span></div><p>${E(t.description||'')}</p><small>${E(t.supervisor_name||'')} · ${E(t.project_name||'')} · ${E(t.due_date||'')}</small><div class="actions"><button class="light" data-spu-edit-task="${t.id}">تعديل</button></div></article>`).join('')}
function clear(){['spuTaskId','spuTaskTitle','spuTaskDescription','spuTaskAdminNotes','spuTaskDue'].forEach(id=>$(id).value='');$('spuTaskSupervisor').value='';$('spuTaskProject').value='';$('spuTaskPriority').value='normal'}
function edit(id){const t=state.tasks.find(x=>S(x.id)===S(id));if(!t)return;$('spuTaskId').value=t.id;$('spuTaskSupervisor').value=t.assigned_supervisor_id||'';$('spuTaskProject').value=t.project_id||'';$('spuTaskTitle').value=t.title||'';$('spuTaskDescription').value=t.description||'';$('spuTaskPriority').value=t.priority||'normal';$('spuTaskDue').value=t.due_date?new Date(t.due_date).toISOString().slice(0,16):'';$('spuTaskAdminNotes').value=t.admin_notes||''}
async function save(){const payload={assigned_supervisor_id:Number($('spuTaskSupervisor').value),project_id:$('spuTaskProject').value?Number($('spuTaskProject').value):null,title:$('spuTaskTitle').value,description:$('spuTaskDescription').value,priority:$('spuTaskPriority').value,due_date:$('spuTaskDue').value?new Date($('spuTaskDue').value).toISOString():null,admin_notes:$('spuTaskAdminNotes').value,status:'new'};if(!payload.assigned_supervisor_id||!payload.title)return notify('اختر المشرف واكتب عنوان المهمة','err');const sb=await waitSb(),b=$('spuTaskSave');b.disabled=true;state.requests++;try{const {data,error}=await sb.rpc('tasneef_admin_save_task_v10850',{p_session_token:token()||null,p_task_id:$('spuTaskId').value?Number($('spuTaskId').value):null,p_payload:payload,p_idempotency_key:crypto.randomUUID?.()||String(Date.now())});if(error)throw error;if(data?.ok===false)throw new Error(data.message);clear();await loadTasks();state.bc?.postMessage({event:'supervisor_portal_tasks_v10850',supervisorId:payload.assigned_supervisor_id});notify('تم حفظ المهمة وظهرت للمشرف')}catch(e){notify(e.message||e,'err')}finally{b.disabled=false}}
function bind(){$('spuAdminTaskRefresh').onclick=loadTasks;$('spuTaskFilterBtn').onclick=loadTasks;$('spuTaskSave').onclick=save;$('spuTaskClear').onclick=clear;$('spuAdminTaskList').onclick=e=>{const b=e.target.closest('[data-spu-edit-task]');if(b)edit(b.dataset.spuEditTask)}}
async function openPage(){ensurePage();safeCall(['showPage'],'adminTasks',document.querySelector('[data-page="adminTasks"]'));try{await loadOptions();await loadTasks()}catch(e){$('spuAdminTaskState').textContent=e.message||e}}
function refreshAdmin(event){if(event==='project_worker_visits'||event==='time_logs')safeCall(['loadDaily','refreshDaily','refreshAll']);else if(event==='attendance')safeCall(['loadAttendance','renderAttendance','refreshAll']);else if(event==='tickets')safeCall(['loadTickets','loadTicketsV10519','renderTickets','refreshAll']);else if(event==='orders')safeCall(['OrdersUI.refresh']);else if(event==='client_reports')safeCall(['loadClientReports','refreshAll']);else if(event==='supervisor_portal_tasks_v10850'&&$('adminTasks')&&!$('adminTasks').classList.contains('hidden'))loadTasks().catch(()=>{});}
async function init(){await waitSb();window.tasneefAdminTasksV10121={openPage,load:loadTasks,version:BUILD};try{state.bc=new BroadcastChannel('tasneef-supervisor-portal-unified-v10850');state.bc.onmessage=e=>refreshAdmin(S(e.data?.event))}catch(_){}const tables=['project_worker_visits','time_logs','attendance','tickets','supervisor_portal_tasks_v10850','client_reports'];tables.forEach(table=>{try{window.sb.channel(`admin-spu-${table}`).on('postgres_changes',{event:'*',schema:'public',table},()=>refreshAdmin(table)).subscribe()}catch(_){}});console.info(BUILD,{legacySupervisorRuntimeLoaded:false,requests:state.requests})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,0),{once:true});else setTimeout(init,0);
})();
