(function(){
'use strict';
if(window.__SupervisorPortalUnifiedV10850) return;
window.__SupervisorPortalUnifiedV10850=true;

const BUILD='V10850-SUPERVISOR-PORTAL-UNIFIED';
const SUPABASE_URL='https://zmjdqiswytxlbfgnfjfv.supabase.co';
const SUPABASE_KEY='sb_publishable_ADsAC5MtBCusDgX62c8NaQ_LyyuTPeb';
const TOKEN_KEYS=['tasneef_session_token_v10817','tasneef_permission_session_v10817'];
const SESSION_TOKEN=()=>TOKEN_KEYS.map(k=>localStorage.getItem(k)||'').find(Boolean)||'';
const $=id=>document.getElementById(id);
const S=v=>String(v??'').trim();
const N=v=>{const n=Number(v);return Number.isFinite(n)?n:0};
const esc=v=>S(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Riyadh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const nowLabel=v=>{try{return new Intl.DateTimeFormat('ar-SA',{timeZone:'Asia/Riyadh',dateStyle:'medium',timeStyle:'short'}).format(new Date(v));}catch(_){return S(v)}};
const uuid=()=>crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const token=SESSION_TOKEN();
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{global:{headers:token?{'x-tasneef-session':token}:{}},auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
window.SupervisorPortalSupabase=sb;

const state={session:null,projects:[],workers:[],logs:[],openVisits:[],attendance:[],tickets:[],tasks:[],orders:[],reports:[],summary:null,section:'checkin',loaded:new Set(),cache:new Map(),inflight:new Map(),selectedWorkers:new Set(),channels:[],sound:false,bc:null,requestSeq:0,disposed:false};
const PERM={
  access:'supervisor_portal.access',checkinView:'supervisor_checkin.view',checkinCreate:'supervisor_checkin.create',checkout:'supervisor_checkout.create',checkoutManual:'supervisor_checkout.manual',delay:'supervisor_delay_reason.submit',
  attendanceView:'supervisor_attendance.view',attendanceCreate:'supervisor_attendance.create',attendanceEdit:'supervisor_attendance.edit',
  ticketsView:'supervisor_tickets.view',ticketsCreate:'supervisor_tickets.create',ticketsEdit:'supervisor_tickets.edit',ticketsClose:'supervisor_tickets.close',
  tasksView:'supervisor_tasks.view',tasksUpdate:'supervisor_tasks.update',tasksComplete:'supervisor_tasks.complete',
  ordersView:'supervisor_orders.view',ordersCreate:'supervisor_orders.create',ordersUpdate:'supervisor_orders.update',ordersFinancial:'supervisor_orders.view_financial',
  summaryView:'supervisor_daily_summary.view',reportsView:'supervisor_daily_report.view',reportsCreate:'supervisor_daily_report.create',reportsEdit:'supervisor_daily_report.edit'
};
function has(key){const p=state.session?.permissions||{};return p[key]===true||p[key]==='true'||state.session?.isSuperAdmin===true;}
function cacheKey(section,date=today()){return ['supervisor-portal',state.session?.userId||'',state.session?.supervisorId||'',section,date].join(':');}
function setCache(section,data,date){state.cache.set(cacheKey(section,date),{data,at:Date.now()});}
function getCache(section,date,maxAge=30000){const c=state.cache.get(cacheKey(section,date));return c&&Date.now()-c.at<maxAge?c.data:null;}
function invalidate(sections=[]){for(const key of [...state.cache.keys()])if(sections.some(s=>key.includes(`:${s}:`)))state.cache.delete(key);sections.forEach(s=>state.loaded.delete(s));}
function setMessage(text,type=''){const el=$('globalMessage');if(!el)return;el.textContent=text;el.className=`portal-message ${type}`.trim();el.classList.toggle('hidden',!text);if(text)setTimeout(()=>{if(el.textContent===text)el.classList.add('hidden')},6500);}
function stateBox(id,text,type=''){const el=$(id);if(!el)return;el.className=`state-box ${type}`.trim();el.textContent=text;}
function rpcError(error,data){let m=S(data?.message||error?.message||error?.details||error);if(/does not exist|PGRST202|42883/i.test(m))m='ملفات Supabase الخاصة بنسخة المشرف الموحدة لم تُثبت بعد.';return m||'تعذر تنفيذ العملية';}
async function rpc(name,args={},key=name){const requestId=++state.requestSeq;state.inflight.set(key,requestId);const {data,error}=await sb.rpc(name,args);if(state.disposed||state.inflight.get(key)!==requestId)throw Object.assign(new Error('STALE_REQUEST'),{stale:true});if(error)throw new Error(rpcError(error));if(data&&data.ok===false)throw new Error(data.message||'تعذر تنفيذ العملية');return data;}
async function uploadFiles(files,folder){const out=[];for(const f of [...(files||[])]){if(f.size>8*1024*1024)throw new Error(`الملف ${f.name} أكبر من 8MB`);const safe=S(f.name).replace(/[^a-zA-Z0-9._-]+/g,'_').slice(-100)||'file';const path=`${state.session.supervisorId}/${folder}/${Date.now()}-${uuid()}-${safe}`;const {error}=await sb.storage.from('supervisor-portal-files-v10850').upload(path,f,{upsert:false,contentType:f.type||undefined});if(error)throw error;out.push({bucket:'supervisor-portal-files-v10850',path,name:f.name,type:f.type,size:f.size});}return out;}
function projectById(id){return state.projects.find(p=>S(p.project_id||p.id)===S(id));}
function workerById(id){return state.workers.find(w=>S(w.employee_id||w.worker_id||w.id)===S(id));}
function projectName(id){return projectById(id)?.project_name||projectById(id)?.name||'-';}
function workerName(id){const w=workerById(id);return w?.employee_name||w?.worker_name||w?.name||`#${id}`;}
function dateValue(id){return $(id)?.value||today();}
function selectedWorkerIds(selector='input[data-worker-id]:checked'){return [...document.querySelectorAll(selector)].map(x=>S(x.dataset.workerId)).filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i);}

const SupervisorPortalService={
  version:BUILD,
  async resolveSession(){return rpc('tasneef_supervisor_portal_resolve_session_v10850',{p_session_token:SESSION_TOKEN()||null},'resolve-session');},
  async getProjects(selectedDate=today(),force=false){if(!force){const c=getCache('projects',selectedDate);if(c)return c.projects;}const d=await rpc('tasneef_supervisor_portal_scope_v10850',{p_session_token:SESSION_TOKEN()||null,p_selected_date:selectedDate},`scope:${selectedDate}`);setCache('projects',d,selectedDate);return d.projects||[];},
  async getWorkers(selectedDate=today(),force=false){if(!force){const c=getCache('workers',selectedDate);if(c)return c.workers;}const d=await rpc('tasneef_supervisor_portal_scope_v10850',{p_session_token:SESSION_TOKEN()||null,p_selected_date:selectedDate},`scope:${selectedDate}`);setCache('workers',d,selectedDate);return d.workers||[];},
  async getScope(selectedDate=today(),force=false){if(!force){const c=getCache('scope',selectedDate);if(c)return c;}const d=await rpc('tasneef_supervisor_portal_scope_v10850',{p_session_token:SESSION_TOKEN()||null,p_selected_date:selectedDate},`scope:${selectedDate}`);setCache('scope',d,selectedDate);return d;},
  async getOpenAttendance(selectedDate=today(),force=false){if(!force){const c=getCache('logs',selectedDate);if(c)return c;}const d=await rpc('tasneef_supervisor_portal_logs_v10850',{p_session_token:SESSION_TOKEN()||null,p_selected_date:selectedDate},`logs:${selectedDate}`);setCache('logs',d,selectedDate);return d;},
  async checkIn(projectId,workerIds,payload){return rpc('tasneef_supervisor_portal_checkin_v10850',{p_session_token:SESSION_TOKEN()||null,p_project_id:Number(projectId),p_worker_ids:workerIds.map(Number),p_visit_type:payload.visitType||null,p_travel_minutes:N(payload.travelMinutes),p_notes:payload.notes||null,p_idempotency_key:payload.key},'write-checkin');},
  async checkOut(projectId,workerIds,payload){return rpc('tasneef_supervisor_portal_checkout_v10850',{p_session_token:SESSION_TOKEN()||null,p_project_id:Number(projectId),p_worker_ids:workerIds.map(Number),p_delay_reason:payload.delayReason||null,p_notes:payload.notes||null,p_idempotency_key:payload.key},'write-checkout');},
  async getDailyAttendance(date=today(),projectId=null,force=false){const ck=`attendance:${projectId||'all'}`;if(!force){const c=getCache(ck,date);if(c)return c;}const d=await rpc('tasneef_supervisor_portal_attendance_v10850',{p_session_token:SESSION_TOKEN()||null,p_selected_date:date,p_project_id:projectId?Number(projectId):null},`attendance:${date}:${projectId||0}`);setCache(ck,d,date);return d;},
  async saveAttendance(date,entries){return rpc('tasneef_supervisor_portal_save_attendance_v10850',{p_session_token:SESSION_TOKEN()||null,p_selected_date:date,p_entries:entries,p_idempotency_key:uuid()},'write-attendance');},
  async getTickets(filters={},force=false){const k=`tickets:${JSON.stringify(filters)}`;if(!force){const c=getCache(k,filters.from||today());if(c)return c;}const d=await rpc('tasneef_supervisor_portal_tickets_v10850',{p_session_token:SESSION_TOKEN()||null,p_project_id:filters.project?Number(filters.project):null,p_status:filters.status||null,p_date_from:filters.from||null,p_date_to:filters.to||null},'tickets');setCache(k,d,filters.from||today());return d;},
  async saveTicket(payload){return rpc('tasneef_supervisor_portal_save_ticket_v10850',{p_session_token:SESSION_TOKEN()||null,p_ticket_id:payload.id?Number(payload.id):null,p_payload:payload,p_idempotency_key:payload.idempotency_key||uuid()},'write-ticket');},
  async getTasks(filters={},force=false){const k=`tasks:${filters.status||''}:${filters.search||''}`;if(!force){const c=getCache(k,today());if(c)return c;}const d=await rpc('tasneef_supervisor_portal_tasks_v10850',{p_session_token:SESSION_TOKEN()||null,p_status:filters.status||null,p_search:filters.search||null},'tasks');setCache(k,d,today());return d;},
  async updateTask(id,payload){return rpc('tasneef_supervisor_portal_update_task_v10850',{p_session_token:SESSION_TOKEN()||null,p_task_id:Number(id),p_payload:payload,p_idempotency_key:uuid()},'write-task');},
  async getOrders(filters={},force=false){const k=`orders:${filters.project||''}:${filters.status||''}`;if(!force){const c=getCache(k,today());if(c)return c;}const d=await rpc('tasneef_supervisor_portal_orders_v10850',{p_session_token:SESSION_TOKEN()||null,p_project_id:filters.project?Number(filters.project):null,p_status:filters.status||null},'orders');setCache(k,d,today());return d;},
  async createOrder(payload){const p=projectById(payload.project_id);const body={project_id:Number(payload.project_id),project_name:p?.project_name||p?.name,order_type:'داخلي',customer_type:'داخلي',customer_name:payload.customer_name,customer_phone:payload.customer_phone,unit_number:payload.unit_number,executor:payload.executor||null,details:payload.details,notes:payload.notes,order_date:today(),execution_status:'لم ينفذ',payment_status:'غير مسدد',created_by:state.session.userId,created_by_name:state.session.supervisorName};const {data,error}=await sb.rpc('orders_create_v10800',{p_payload:body,p_actor_id:S(state.session.userId),p_actor_name:state.session.supervisorName,p_request_id:uuid()});if(error)throw new Error(rpcError(error));return data;},
  async updateOrder(id,payload,reason){const {data,error}=await sb.rpc('orders_update_v10800',{p_order_id:Number(id),p_payload:payload,p_actor_id:S(state.session.userId),p_actor_name:state.session.supervisorName,p_reason:reason||'تحديث من نسخة المشرف الموحدة'});if(error)throw new Error(rpcError(error));return data;},
  async uploadOrderReceipt(id,file){if(!file)return null;if(file.size>5*1024*1024)throw new Error('الإيصال أكبر من 5MB');const safe=S(file.name).replace(/[^a-zA-Z0-9._-]+/g,'_');const path=`orders/${id}/receipts/${Date.now()}-${uuid()}-${safe}`;const up=await sb.storage.from('order-receipts').upload(path,file,{upsert:false,contentType:file.type||undefined});if(up.error)throw up.error;const {data,error}=await sb.rpc('orders_add_attachment_v10800',{p_order_id:Number(id),p_bucket:'order-receipts',p_path:path,p_file_name:file.name,p_mime_type:file.type,p_file_size:file.size,p_actor_id:S(state.session.userId),p_actor_name:state.session.supervisorName});if(error)throw new Error(rpcError(error));return data;},
  async getDailySummary(date=today(),force=false){if(!force){const c=getCache('summary',date);if(c)return c;}const d=await rpc('tasneef_supervisor_portal_summary_v10850',{p_session_token:SESSION_TOKEN()||null,p_selected_date:date},`summary:${date}`);setCache('summary',d,date);return d;},
  async getDailyReports(date=null,force=false){const key=`reports:${date||'all'}`;if(!force){const c=getCache(key,date||today());if(c)return c;}const d=await rpc('tasneef_supervisor_portal_reports_v10850',{p_session_token:SESSION_TOKEN()||null,p_selected_date:date},'reports');setCache(key,d,date||today());return d;},
  async saveDailyReport(payload){return rpc('tasneef_supervisor_portal_save_report_v10850',{p_session_token:SESSION_TOKEN()||null,p_report_id:payload.id?Number(payload.id):null,p_payload:payload,p_idempotency_key:payload.idempotency_key||uuid()},'write-report');},
  closeEditor(){}
};
window.SupervisorPortalService=SupervisorPortalService;

function fillProjects(){const selects=['checkinProject','attendanceProject','ticketProject','ticketFilterProject','orderProject','orderFilterProject','reportProject'];for(const id of selects){const el=$(id);if(!el)continue;const first=['attendanceProject','ticketFilterProject','orderFilterProject'].includes(id)?'<option value="">كل مشاريع المشرف</option>':'<option value="">اختر المشروع</option>';el.innerHTML=first+state.projects.map(p=>`<option value="${esc(p.project_id||p.id)}">${esc(p.project_name||p.name)}</option>`).join('');}}
function renderWorkerRow(w,{selectable=true,inside=false}={}){const id=S(w.employee_id||w.worker_id||w.id);return `<label class="worker-row"><input type="checkbox" data-worker-id="${esc(id)}" ${selectable?'':'disabled'}><span><b>${esc(w.employee_name||w.worker_name||w.name)}</b><small>${esc(w.employee_code||w.worker_employee_code||'')} · ${esc(w.role_type||'عامل')}${w.project_name?` · ${esc(w.project_name)}`:''}${inside&&w.open_project_name?` · داخل ${esc(w.open_project_name)}`:''}</small></span></label>`;}
function workerStateFor(w,projectId){const id=S(w.employee_id||w.worker_id||w.id);const open=state.openVisits.find(v=>S(v.employee_id||v.worker_id)===id&&!v.check_out);if(!open)return 'available';return S(open.project_id)===S(projectId)?'inside':'other';}
function renderWorkers(){const pid=$('checkinProject')?.value;const all=state.workers;const inProject=all.filter(w=>workerStateFor(w,pid)==='inside');const avail=all.filter(w=>workerStateFor(w,pid)==='available');const other=all.filter(w=>workerStateFor(w,pid)==='other');$('workersTotalKpi').textContent=all.length;$('workersInsideKpi').textContent=inProject.length;$('workersAvailableKpi').textContent=avail.length;$('workersOtherProjectKpi').textContent=other.length;$('allWorkersList').innerHTML=all.length?all.map(w=>renderWorkerRow(w,{selectable:false,inside:true})).join(''):'<div class="state-box empty">لا يوجد عمال في التوزيع الفعال.</div>';$('insideWorkersList').innerHTML=inProject.length?inProject.map(w=>renderWorkerRow(w)).join(''):'<div class="state-box empty">لا يوجد عمال داخل المشروع الآن.</div>';$('availableWorkersList').innerHTML=avail.length?avail.map(w=>renderWorkerRow(w)).join(''):'<div class="state-box empty">لا يوجد عمال متاحون.</div>';}
function requiredMinutes(p,date){const d=new Date(`${date}T12:00:00+03:00`);return d.getDay()===5?N(p.friday_minutes):N(p.required_daily_minutes);}
function renderTimeCard(){const id=$('checkinProject')?.value;const p=projectById(id);const el=$('projectTimeCard');if(!p){el.innerHTML='<div class="state-box">اختر مشروعًا لعرض الوقت المطلوب وحالة التسجيل.</div>';return;}const open=state.logs.find(l=>S(l.project_id)===S(id)&&!l.check_out);const req=requiredMinutes(p,dateValue('checkinDate'));let remaining=req;if(open)remaining=Math.max(0,req-Math.floor((Date.now()-new Date(open.check_in).getTime())/60000));const expected=open&&req?new Date(new Date(open.check_in).getTime()+req*60000):null;el.innerHTML=`<div class="time-card-head"><b>${esc(p.project_name||p.name)}</b><span class="pill ${open?'green':''}">${open?'تسجيل مفتوح':'لا يوجد تسجيل مفتوح'}</span></div><div class="time-card-grid"><div><small>نوع التشغيل</small><b>${esc(p.operation_type||'-')}</b></div><div><small>المدة المطلوبة</small><b>${req} دقيقة</b></div><div><small>وقت الدخول</small><b>${open?nowLabel(open.check_in):'-'}</b></div><div><small>الخروج المتوقع / المتبقي</small><b>${expected?nowLabel(expected):'-'}${open?` · ${remaining} د`:''}</b></div></div>`;}
function renderLogs(){const list=$('todayLogsList');const rows=state.logs||[];stateBox('todayLogsState',rows.length?`تم تحميل ${rows.length} سجلًا.`:'لا توجد سجلات لهذا اليوم.',rows.length?'':'empty');list.innerHTML=rows.map(l=>`<article class="item ${l.check_out?'ok':'warn'}"><div class="item-head"><b>${esc(l.project_name||projectName(l.project_id))}</b><span class="pill ${l.check_out?'green':'amber'}">${l.check_out?'مغلق':'مفتوح'}</span></div><div class="item-meta"><span>الدخول: ${esc(nowLabel(l.check_in))}</span><span>الخروج: ${l.check_out?esc(nowLabel(l.check_out)):'—'}</span><span>المدة: ${N(l.duration_minutes)} دقيقة</span></div></article>`).join('');}
async function loadScope(force=false){const d=await SupervisorPortalService.getScope(dateValue('checkinDate'),force);state.projects=d.projects||[];state.workers=d.workers||[];fillProjects();return d;}
async function loadCheckin(force=false){stateBox('todayLogsState','جاري تحميل السجلات…');try{await loadScope(force);const d=await SupervisorPortalService.getOpenAttendance(dateValue('checkinDate'),force);state.logs=d.logs||[];state.openVisits=d.open_visits||[];renderWorkers();renderTimeCard();renderLogs();state.loaded.add('checkin');}catch(e){if(!e.stale){stateBox('todayLogsState',e.message,'error');setMessage(e.message,'error')}}}

function renderAttendance(){const rows=state.attendance||[];const box=$('attendanceRows');stateBox('attendanceState',rows.length?`تم تحميل ${rows.length} عاملًا.`:'لا يوجد عمال مطابقون للتوزيع.',rows.length?'':'empty');box.innerHTML=rows.map(r=>`<div class="attendance-row" data-att-worker="${esc(r.employee_id)}" data-project-id="${esc(r.project_id||'')}"><div class="name"><b>${esc(r.employee_name)}</b><small>${esc(r.employee_code||'')} · ${esc(r.project_name||'-')}</small></div><select data-att-status><option value="present" ${r.attendance_status==='present'?'selected':''}>حاضر</option><option value="absent" ${r.attendance_status==='absent'?'selected':''}>غائب</option><option value="leave" ${r.attendance_status==='leave'?'selected':''}>إجازة</option><option value="rest" ${r.attendance_status==='rest'?'selected':''}>راحة</option><option value="mission" ${r.attendance_status==='mission'?'selected':''}>مأمورية</option><option value="suspended" ${r.attendance_status==='suspended'?'selected':''}>موقوف</option></select><input data-att-note placeholder="ملاحظات" value="${esc(r.notes||'')}"></div>`).join('');}
async function loadAttendance(force=false){stateBox('attendanceState','جاري تحميل الحضور…');try{const d=await SupervisorPortalService.getDailyAttendance(dateValue('attendanceDate'),$('attendanceProject')?.value||null,force);state.attendance=d.rows||[];renderAttendance();state.loaded.add('attendance');}catch(e){if(!e.stale)stateBox('attendanceState',e.message,'error')}}

function statusArabic(s){return ({open:'مفتوحة',processing:'تحت المعالجة',closed:'مغلقة',new:'جديدة',in_progress:'قيد التنفيذ',completed:'مكتملة',overdue:'متأخرة',cancelled:'ملغاة',review:'تحتاج مراجعة'})[S(s)]||S(s)||'-';}
function renderTickets(){const rows=state.tickets||[];stateBox('ticketsState',rows.length?`تم تحميل ${rows.length} تذكرة.`:'لا توجد تذاكر مطابقة.',rows.length?'':'empty');$('ticketsList').innerHTML=rows.map(t=>`<article class="item ${t.priority==='urgent'?'danger':t.status==='closed'?'ok':'warn'}"><div class="item-head"><b>${esc(t.ticket_number||`T-${t.id}`)} — ${esc(t.title||t.category)}</b><span class="pill ${t.status==='closed'?'green':t.priority==='urgent'?'red':'amber'}">${esc(statusArabic(t.status))}</span></div><div class="item-meta"><span>${esc(t.project_name||projectName(t.project_id))}</span><span>${esc(t.category||'-')}</span><span>${esc(nowLabel(t.created_at))}</span></div><p>${esc(t.description||'')}</p><div class="actions"><button type="button" class="light" data-ticket-edit="${t.id}">تعديل</button>${t.status!=='closed'&&has(PERM.ticketsClose)?`<button type="button" data-ticket-close="${t.id}">إغلاق</button>`:''}</div></article>`).join('');}
async function loadTickets(force=false){stateBox('ticketsState','جاري تحميل التذاكر…');try{const d=await SupervisorPortalService.getTickets({project:$('ticketFilterProject')?.value,status:$('ticketFilterStatus')?.value,from:$('ticketFilterFrom')?.value,to:$('ticketFilterTo')?.value},force);state.tickets=d.rows||[];renderTickets();state.loaded.add('tickets');}catch(e){if(!e.stale)stateBox('ticketsState',e.message,'error')}}
function clearTicket(){['ticketId','ticketTitle','ticketBuilding','ticketFloor','ticketUnit','ticketDescription'].forEach(id=>{if($(id))$(id).value=''});$('ticketStatus').value='open';$('ticketFiles').value='';$('ticketFilesPreview').innerHTML='';}
function editTicket(id){const t=state.tickets.find(x=>S(x.id)===S(id));if(!t)return;for(const [id2,v] of Object.entries({ticketId:t.id,ticketProject:t.project_id,ticketCategory:t.category,ticketPriority:t.priority,ticketStatus:t.status,ticketTitle:t.title,ticketBuilding:t.building,ticketFloor:t.floor,ticketUnit:t.unit,ticketDescription:t.description}))if($(id2))$(id2).value=v??'';window.scrollTo({top:0,behavior:'smooth'});}

function openTaskUpdateModal(taskId,status){const t=state.tasks.find(x=>S(x.id)===S(taskId));if(!t)return;$('portalModalTitle').textContent=`تحديث المهمة: ${t.title}`;$('portalModalBody').innerHTML=`<label>الحالة</label><select id="modalTaskStatus"><option value="in_progress">قيد التنفيذ</option><option value="review">تحتاج مراجعة</option><option value="completed">مكتملة</option></select><label>التحديث / الملاحظة</label><textarea id="modalTaskNote"></textarea><label>صورة أو ملف</label><input id="modalTaskFile" type="file" accept="image/*,application/pdf"><div class="actions"><button id="modalTaskSave">حفظ التحديث</button></div>`;$('modalTaskStatus').value=status;$('portalModal').classList.remove('hidden');$('modalTaskSave').onclick=async()=>{const b=$('modalTaskSave');b.disabled=true;try{const files=await uploadFiles($('modalTaskFile').files,`tasks/${taskId}`);await SupervisorPortalService.updateTask(taskId,{status:$('modalTaskStatus').value,note:$('modalTaskNote').value,attachments:files});$('portalModal').classList.add('hidden');invalidate(['tasks','summary']);broadcast('supervisor_portal_tasks_v10850');await loadTasks(true);setMessage('تم تحديث المهمة');}catch(e){setMessage(e.message,'error')}finally{b.disabled=false}};}
function renderTasks(){const rows=state.tasks||[];stateBox('tasksState',rows.length?`تم تحميل ${rows.length} مهمة.`:'لا توجد مهام مطابقة.',rows.length?'':'empty');$('tasksList').innerHTML=rows.map(t=>`<article class="item ${t.status==='overdue'?'danger':t.status==='completed'?'ok':'warn'}"><div class="item-head"><b>${esc(t.title)}</b><span class="pill">${esc(statusArabic(t.status))}</span></div><p>${esc(t.description||'')}</p><div class="item-meta"><span>الأولوية: ${esc(t.priority||'-')}</span><span>الموعد: ${esc(t.due_date||'-')}</span><span>${esc(t.project_name||'')}</span></div><div class="actions"><button type="button" data-task-action="${t.id}" data-status="in_progress">بدء</button><button type="button" data-task-action="${t.id}" data-status="review">تحتاج مراجعة</button><button type="button" data-task-action="${t.id}" data-status="completed">إنهاء</button></div></article>`).join('');}
async function loadTasks(force=false){stateBox('tasksState','جاري تحميل المهام…');try{const d=await SupervisorPortalService.getTasks({status:$('taskFilterStatus')?.value,search:$('taskSearch')?.value},force);state.tasks=d.rows||[];renderTasks();state.loaded.add('tasks');}catch(e){if(!e.stale)stateBox('tasksState',e.message,'error')}}

function renderOrders(){const rows=state.orders||[];stateBox('ordersState',rows.length?`تم تحميل ${rows.length} أوردرًا.`:'لا توجد أوردرات مطابقة.',rows.length?'':'empty');$('ordersList').innerHTML=rows.map(o=>`<article class="item ${S(o.execution_status).includes('تم التنفيذ')?'ok':'warn'}"><div class="item-head"><b>${esc(o.order_number||o.number||`ORD${o.id}`)}</b><span class="pill">${esc(o.execution_status||o.status||'-')}</span></div><div class="item-meta"><span>${esc(o.project_name||'-')}</span><span>${esc(o.customer_name||'-')}</span><span>${esc(o.executor||'-')}</span></div><p>${esc(o.details||o.description||'')}</p>${has(PERM.ordersFinancial)?`<div class="item-meta"><span>الإجمالي: ${esc(o.total_amount||o.total||0)} ر.س</span><span>السداد: ${esc(o.payment_status||'-')}</span></div>`:''}${has(PERM.ordersUpdate)?`<div class="actions"><button type="button" class="light" data-order-status="${o.id}" data-value="قيد التنفيذ">بدء التنفيذ</button><button type="button" data-order-status="${o.id}" data-value="تم التنفيذ">تم التنفيذ</button><label class="light" style="padding:8px;border-radius:10px;cursor:pointer">رفع إيصال<input hidden type="file" data-order-receipt="${o.id}" accept="image/*,application/pdf"></label></div>`:''}</article>`).join('');}
async function loadOrders(force=false){stateBox('ordersState','جاري تحميل الأوردرات…');try{const d=await SupervisorPortalService.getOrders({project:$('orderFilterProject')?.value,status:$('orderFilterStatus')?.value},force);state.orders=d.rows||[];renderOrders();state.loaded.add('orders');}catch(e){if(!e.stale)stateBox('ordersState',e.message,'error')}}

function renderSummary(){const d=state.summary||{};const k=[['المشاريع التي تمت زيارتها',d.visited_projects],['العمال الحاضرون',d.present_workers],['الغائبون',d.absent_workers],['داخل المشاريع',d.workers_inside],['تسجيلات مفتوحة',d.open_logs],['تسجيلات خروج',d.closed_logs],['تذاكر جديدة',d.new_tickets],['تذاكر مغلقة',d.closed_tickets],['الأوردرات',d.orders_count],['مهام مكتملة',d.completed_tasks],['حالات التأخير',d.delays],['الوقت الزائد',d.extra_time_count]];$('summaryKpis').innerHTML=k.map(([a,b])=>`<div class="kpi"><small>${a}</small><b>${N(b)}</b></div>`).join('');$('summaryDetails').innerHTML=(d.unvisited_projects||[]).length?`<article class="item warn"><b>مشاريع لم تتم زيارتها</b><p>${(d.unvisited_projects||[]).map(x=>esc(x.project_name||x.name)).join('، ')}</p></article>`:'<article class="item ok"><b>جميع المشاريع المطلوبة تمت زيارتها.</b></article>';stateBox('summaryState','تم تحديث الملخص من بيانات اليوم الحقيقية.');}
async function loadSummary(force=false){stateBox('summaryState','جاري احتساب الملخص…');try{state.summary=await SupervisorPortalService.getDailySummary(dateValue('summaryDate'),force);renderSummary();state.loaded.add('summary');}catch(e){if(!e.stale)stateBox('summaryState',e.message,'error')}}

function renderReports(){const rows=state.reports||[];stateBox('reportsState',rows.length?`تم تحميل ${rows.length} تقريرًا.`:'لا توجد تقارير.',rows.length?'':'empty');$('reportsList').innerHTML=rows.map(r=>`<article class="item ok"><div class="item-head"><b>${esc(r.project_name||projectName(r.project_id))} — ${esc(r.report_date)}</b><span class="pill">${esc(r.status||'مرسل')}</span></div><p><b>المنفذ:</b> ${esc(r.completed_work||r.executive_summary||'')}</p><div class="actions">${has(PERM.reportsEdit)?`<button class="light" data-report-edit="${r.id}">تعديل</button>`:''}</div></article>`).join('');}
async function loadReports(force=false){stateBox('reportsState','جاري تحميل التقارير…');try{const d=await SupervisorPortalService.getDailyReports(null,force);state.reports=d.rows||[];renderReports();state.loaded.add('reports');}catch(e){if(!e.stale)stateBox('reportsState',e.message,'error')}}
function clearReport(){['reportId','reportCompleted','reportPending','reportIssues','reportAdminNeeds','reportNotes'].forEach(id=>$(id).value='');$('reportDate').value=today();$('reportFiles').value='';$('reportFilesPreview').innerHTML='';}
function editReport(id){const r=state.reports.find(x=>S(x.id)===S(id));if(!r)return;const map={reportId:r.id,reportProject:r.project_id,reportDate:r.report_date,reportCompleted:r.completed_work,reportPending:r.pending_work,reportIssues:r.issues,reportAdminNeeds:r.admin_needs,reportNotes:r.notes};for(const [id2,v] of Object.entries(map))if($(id2))$(id2).value=v??'';}

async function loadSection(name,force=false){if(name==='checkin')return loadCheckin(force);if(name==='attendance')return loadAttendance(force);if(name==='tickets')return loadTickets(force);if(name==='tasks')return loadTasks(force);if(name==='orders')return loadOrders(force);if(name==='summary')return loadSummary(force);if(name==='reports')return loadReports(force);}
function activateSection(name){state.section=name;document.querySelectorAll('.portal-tab').forEach(b=>b.classList.toggle('active',b.dataset.section===name));document.querySelectorAll('.portal-page').forEach(p=>p.classList.toggle('active',p.dataset.page===name));loadSection(name,false);}
function applyPermissions(){const rules={checkin:PERM.checkinView,attendance:PERM.attendanceView,tickets:PERM.ticketsView,tasks:PERM.tasksView,orders:PERM.ordersView,summary:PERM.summaryView,reports:PERM.reportsView};document.querySelectorAll('.portal-tab').forEach(b=>{b.hidden=!has(rules[b.dataset.section])});$('checkinBtn').hidden=!has(PERM.checkinCreate);$('checkoutBtn').hidden=!has(PERM.checkout);$('saveAttendanceBtn').hidden=!(has(PERM.attendanceCreate)||has(PERM.attendanceEdit));$('saveTicketBtn').hidden=!(has(PERM.ticketsCreate)||has(PERM.ticketsEdit));$('saveOrderBtn').hidden=!has(PERM.ordersCreate);$('saveReportBtn').hidden=!(has(PERM.reportsCreate)||has(PERM.reportsEdit));const first=[...document.querySelectorAll('.portal-tab')].find(x=>!x.hidden);if(first&&!has(rules.checkin))activateSection(first.dataset.section);}
function alertRows(summary){const rows=[];if(summary?.open_logs)rows.push({key:'open',text:`لديك ${summary.open_logs} تسجيل دخول مفتوح`,cls:'warn'});if(summary?.new_tasks)rows.push({key:'tasks',text:`لديك ${summary.new_tasks} مهمة جديدة`,cls:'warn'});if(summary?.urgent_tickets)rows.push({key:'tickets',text:`لديك ${summary.urgent_tickets} تذكرة عاجلة`,cls:'urgent'});if(summary?.pending_orders)rows.push({key:'orders',text:`يوجد ${summary.pending_orders} أوردر ينتظر التنفيذ`,cls:'warn'});if(summary?.missing_reports)rows.push({key:'reports',text:'يوجد تقرير يومي لم يُرسل',cls:'warn'});return rows;}
function renderAlerts(summary){const rows=alertRows(summary);$('portalAlerts').innerHTML=rows.map(r=>`<div class="portal-alert ${r.cls}"><span>${esc(r.text)}</span></div>`).join('');if(state.sound&&rows.some(r=>r.cls==='urgent'))beep(880);}
let audioCtx=null;function beep(freq=620){try{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=freq;g.gain.value=.06;o.connect(g);g.connect(audioCtx.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.35);o.stop(audioCtx.currentTime+.36);}catch(_){}}
function initSound(){const k=`tasneef-supervisor-sound:${state.session.userId}`;state.sound=localStorage.getItem(k)==='1';$('enableSoundsBtn').textContent=state.sound?'الأصوات مفعلة':'تفعيل الأصوات';$('enableSoundsBtn').onclick=async()=>{try{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();await audioCtx.resume();state.sound=!state.sound;localStorage.setItem(k,state.sound?'1':'0');$('enableSoundsBtn').textContent=state.sound?'الأصوات مفعلة':'تفعيل الأصوات';if(state.sound)beep();}catch(e){setMessage('تعذر تشغيل الصوت في هذا المتصفح','error')}};}
function broadcast(event,payload={}){try{state.bc?.postMessage({event,supervisorId:state.session.supervisorId,...payload});}catch(_){}}
function setupRealtime(){try{state.bc=new BroadcastChannel('tasneef-supervisor-portal-unified-v10850');state.bc.onmessage=e=>handleExternalUpdate(e.data||{});}catch(_){}const tables=['supervisor_project_assignments','monthly_distribution','project_worker_visits','time_logs','attendance','tickets','supervisor_portal_tasks_v10850','client_reports'];tables.forEach(table=>{try{const ch=sb.channel(`spu-${table}-${state.session.supervisorId}`).on('postgres_changes',{event:'*',schema:'public',table},p=>handleExternalUpdate({event:table,payload:p})).subscribe();state.channels.push(ch);}catch(_){}});}
function handleExternalUpdate(msg){const event=S(msg.event);if(event.includes('distribution')||event==='supervisor_project_assignments'){invalidate(['scope','projects','workers','checkin','attendance','summary']);loadScope(true).then(()=>{fillProjects();loadCheckin(true);if(state.section==='attendance')loadAttendance(true)}).catch(()=>{});}else if(event==='project_worker_visits'||event==='time_logs'){invalidate(['logs','summary']);if(state.section==='checkin')loadCheckin(true);if(state.section==='summary')loadSummary(true);}else if(event==='attendance'){invalidate(['attendance','summary']);if(state.section==='attendance')loadAttendance(true);}else if(event==='tickets'){invalidate(['tickets','summary']);if(state.section==='tickets')loadTickets(true);}else if(event.includes('tasks')){invalidate(['tasks','summary']);if(state.section==='tasks')loadTasks(true);}else if(event==='orders'){invalidate(['orders','summary']);if(state.section==='orders')loadOrders(true);}else if(event==='client_reports'){invalidate(['reports','summary']);if(state.section==='reports')loadReports(true);}}
async function logout(){state.disposed=true;state.inflight.clear();state.cache.clear();for(const ch of state.channels)try{await sb.removeChannel(ch)}catch(_){}try{state.bc?.close()}catch(_){}try{await sb.rpc('tasneef_logout_v10817',{p_session_token:SESSION_TOKEN()||null})}catch(_){}for(const k of [...TOKEN_KEYS,'tasneef_user','tasneef_current_user','currentUser'])localStorage.removeItem(k);location.replace('index.html?logout=1&build=10850');}
function bindEvents(){document.querySelectorAll('.portal-tab').forEach(b=>b.addEventListener('click',()=>activateSection(b.dataset.section)));$('logoutBtn').onclick=logout;$('checkinProject').onchange=()=>{renderWorkers();renderTimeCard()};$('checkinDate').onchange=()=>loadCheckin(true);$('refreshCheckinBtn').onclick=()=>loadCheckin(true);
$('checkinBtn').onclick=async()=>{const pid=$('checkinProject').value,ids=selectedWorkerIds('#availableWorkersList input[data-worker-id]:checked');if(!pid)return setMessage('اختر المشروع','error');if(!ids.length)return setMessage('حدد عاملًا واحدًا على الأقل من العمال المتاحين','error');const b=$('checkinBtn');b.disabled=true;try{await SupervisorPortalService.checkIn(pid,ids,{visitType:$('checkinVisitType').value,travelMinutes:$('checkinTravel').value,notes:$('checkinNotes').value,key:uuid()});invalidate(['logs','summary']);broadcast('project_worker_visits',{projectId:pid});await loadCheckin(true);setMessage('تم تسجيل الدخول بنجاح');}catch(e){setMessage(e.message,'error')}finally{b.disabled=false}};
$('checkoutBtn').onclick=async()=>{const pid=$('checkinProject').value,ids=selectedWorkerIds('#insideWorkersList input[data-worker-id]:checked');if(!pid)return setMessage('اختر المشروع','error');if(!ids.length)return setMessage('حدد العمال المطلوب تسجيل خروجهم','error');const b=$('checkoutBtn');b.disabled=true;try{await SupervisorPortalService.checkOut(pid,ids,{delayReason:$('checkinDelayReason').value,notes:$('checkinNotes').value,key:uuid()});invalidate(['logs','summary']);broadcast('project_worker_visits',{projectId:pid});await loadCheckin(true);setMessage('تم تسجيل الخروج بنجاح');}catch(e){setMessage(e.message,'error')}finally{b.disabled=false}};
$('attendanceDate').onchange=()=>loadAttendance(true);$('attendanceProject').onchange=()=>loadAttendance(true);$('refreshAttendanceBtn').onclick=()=>loadAttendance(true);document.querySelectorAll('[data-bulk-attendance]').forEach(b=>b.onclick=()=>document.querySelectorAll('[data-att-status]').forEach(s=>s.value=b.dataset.bulkAttendance));$('saveAttendanceBtn').onclick=async()=>{const rows=[...document.querySelectorAll('[data-att-worker]')].map(r=>({employee_id:Number(r.dataset.attWorker),project_id:r.dataset.projectId?Number(r.dataset.projectId):null,status:r.querySelector('[data-att-status]').value,notes:r.querySelector('[data-att-note]').value}));const b=$('saveAttendanceBtn');b.disabled=true;try{await SupervisorPortalService.saveAttendance(dateValue('attendanceDate'),rows);invalidate(['attendance','summary']);broadcast('attendance');await loadAttendance(true);setMessage('تم حفظ الحضور والغياب');}catch(e){setMessage(e.message,'error')}finally{b.disabled=false}};
$('refreshTicketsBtn').onclick=()=>loadTickets(true);$('clearTicketBtn').onclick=clearTicket;$('saveTicketBtn').onclick=async()=>{const files=await uploadFiles($('ticketFiles').files,'tickets');const payload={id:$('ticketId').value||null,project_id:Number($('ticketProject').value),category:$('ticketCategory').value,priority:$('ticketPriority').value,status:$('ticketStatus').value,title:$('ticketTitle').value,description:$('ticketDescription').value,building:$('ticketBuilding').value,floor:$('ticketFloor').value,unit:$('ticketUnit').value,attachments:files,idempotency_key:uuid()};if(!payload.project_id||!payload.title||!payload.description)return setMessage('المشروع والعنوان والوصف مطلوبة','error');const b=$('saveTicketBtn');b.disabled=true;try{await SupervisorPortalService.saveTicket(payload);invalidate(['tickets','summary']);broadcast('tickets');clearTicket();await loadTickets(true);setMessage('تم حفظ التذكرة');}catch(e){setMessage(e.message,'error')}finally{b.disabled=false}};
$('ticketsList').onclick=async e=>{const edit=e.target.closest('[data-ticket-edit]'),close=e.target.closest('[data-ticket-close]');if(edit)editTicket(edit.dataset.ticketEdit);if(close){const t=state.tickets.find(x=>S(x.id)===S(close.dataset.ticketClose));if(!t)return;try{await SupervisorPortalService.saveTicket({...t,id:t.id,status:'closed',idempotency_key:uuid()});invalidate(['tickets','summary']);broadcast('tickets');await loadTickets(true);setMessage('تم إغلاق التذكرة');}catch(err){setMessage(err.message,'error')}}};
$('refreshTasksBtn').onclick=()=>loadTasks(true);$('tasksList').onclick=e=>{const b=e.target.closest('[data-task-action]');if(b)openTaskUpdateModal(b.dataset.taskAction,b.dataset.status)};
$('refreshOrdersBtn').onclick=()=>loadOrders(true);$('ordersList').onclick=async e=>{const st=e.target.closest('[data-order-status]');if(st){try{await SupervisorPortalService.updateOrder(st.dataset.orderStatus,{execution_status:st.dataset.value},`تحديث الحالة إلى ${st.dataset.value}`);invalidate(['orders','summary']);broadcast('orders');await loadOrders(true);setMessage('تم تحديث حالة الأوردر');}catch(err){setMessage(err.message,'error')}}};$('ordersList').onchange=async e=>{const inp=e.target.closest('[data-order-receipt]');if(!inp||!inp.files?.[0])return;try{await SupervisorPortalService.uploadOrderReceipt(inp.dataset.orderReceipt,inp.files[0]);broadcast('orders');setMessage('تم رفع الإيصال');}catch(err){setMessage(err.message,'error')}};$('saveOrderBtn').onclick=async()=>{const payload={project_id:Number($('orderProject').value),unit_number:$('orderUnit').value,customer_name:$('orderCustomer').value,customer_phone:$('orderPhone').value,executor:$('orderExecutor').value,details:$('orderDetails').value,notes:$('orderNotes').value};if(!payload.project_id||!payload.customer_name||!payload.details)return setMessage('المشروع واسم العميل وتفاصيل الخدمة مطلوبة','error');const b=$('saveOrderBtn');b.disabled=true;try{await SupervisorPortalService.createOrder(payload);invalidate(['orders','summary']);broadcast('orders');['orderUnit','orderCustomer','orderPhone','orderExecutor','orderDetails','orderNotes'].forEach(id=>$(id).value='');await loadOrders(true);setMessage('تم إنشاء الأوردر');}catch(e){setMessage(e.message,'error')}finally{b.disabled=false}};
$('refreshSummaryBtn').onclick=()=>loadSummary(true);$('summaryDate').onchange=()=>loadSummary(true);$('clearReportBtn').onclick=clearReport;$('saveReportBtn').onclick=async()=>{const files=await uploadFiles($('reportFiles').files,'daily-reports');const payload={id:$('reportId').value||null,project_id:Number($('reportProject').value),report_date:$('reportDate').value,completed_work:$('reportCompleted').value,pending_work:$('reportPending').value,issues:$('reportIssues').value,admin_needs:$('reportAdminNeeds').value,notes:$('reportNotes').value,attachments:files,idempotency_key:uuid()};if(!payload.project_id||!payload.report_date||!payload.completed_work)return setMessage('المشروع والتاريخ والأعمال المنفذة مطلوبة','error');const b=$('saveReportBtn');b.disabled=true;try{await SupervisorPortalService.saveDailyReport(payload);invalidate(['reports','summary']);broadcast('client_reports');clearReport();await loadReports(true);setMessage('تم إرسال التقرير اليومي للإدارة');}catch(e){setMessage(e.message,'error')}finally{b.disabled=false}};$('reportsList').onclick=e=>{const b=e.target.closest('[data-report-edit]');if(b)editReport(b.dataset.reportEdit)};$('ticketFiles').onchange=()=>{$('ticketFilesPreview').innerHTML=[...$('ticketFiles').files].map(f=>`<span class="file-chip">${esc(f.name)}</span>`).join('')};$('reportFiles').onchange=()=>{$('reportFilesPreview').innerHTML=[...$('reportFiles').files].map(f=>`<span class="file-chip">${esc(f.name)}</span>`).join('')};$('portalModalClose').onclick=()=>$('portalModal').classList.add('hidden');}
async function initialSummary(){try{const s=await SupervisorPortalService.getDailySummary(today(),true);renderAlerts(s);}catch(_){}}
async function cleanupLegacyRuntime(){
  try{if('serviceWorker' in navigator){const regs=await navigator.serviceWorker.getRegistrations();for(const r of regs){const u=S(r.active?.scriptURL||r.installing?.scriptURL||r.waiting?.scriptURL);if(/tasneef|supervisor|service-worker|sw\.js/i.test(u))await r.unregister();}}}catch(e){console.warn(BUILD,'service worker cleanup',e)}
  try{if(window.caches){const names=await caches.keys();for(const n of names)if(/tasneef|supervisor|v10(8[0-4][0-9]|7)/i.test(n)&&!n.includes('v10850'))await caches.delete(n);}}catch(e){console.warn(BUILD,'cache cleanup',e)}
  const preserve=new Set([...TOKEN_KEYS,'tasneef_user','tasneef_current_user','currentUser',`tasneef-supervisor-sound:${state.session?.userId||''}`]);
  for(let i=localStorage.length-1;i>=0;i--){const k=localStorage.key(i)||'';if(preserve.has(k))continue;if(/supervisor.*(projects|workers|attendance|tickets|orders|tasks|reports|scope|cache)|tasneef_sup_|monthly_distribution_cache/i.test(k))localStorage.removeItem(k);}
}
async function boot(){const loading=$('portalLoadingText');try{await cleanupLegacyRuntime();if(!SESSION_TOKEN())throw new Error('انتهت جلسة الدخول. سجّل الدخول مرة أخرى.');loading.textContent='جارٍ حل هوية المشرف والصلاحيات…';state.session=await SupervisorPortalService.resolveSession();if(!state.session?.supervisorId)throw new Error('تعذر تحديد حساب المشرف المرتبط بهذا المستخدم. راجع إدارة المستخدمين.');if(!state.session.isActive)throw new Error('حساب المشرف موقوف. راجع إدارة المستخدمين.');$('portalTitle').textContent=`لوحة المشرف - ${state.session.supervisorName||''}`;['checkinDate','attendanceDate','summaryDate','reportDate'].forEach(id=>{if($(id))$(id).value=today()});loading.textContent='جارٍ تحميل المشاريع والعمال من التوزيع الموحد…';await loadScope(true);fillProjects();applyPermissions();bindEvents();initSound();setupRealtime();$('portalApp').hidden=false;$('portalLoadingGate').classList.add('hidden');await loadCheckin(true);initialSummary();console.info(BUILD,{authUserId:state.session.authUserId,profileId:state.session.profileId,employeeId:state.session.employeeId,supervisorId:state.session.supervisorId,employeeCode:state.session.employeeCode,supervisorName:state.session.supervisorName,projects:state.projects.length,workers:state.workers.length});}catch(e){loading.textContent=e.message;$('portalLoadingGate').querySelector('.spinner')?.classList.add('hidden');const btn=document.createElement('button');btn.textContent='العودة لتسجيل الدخول';btn.onclick=()=>location.replace('index.html');$('portalLoadingGate').querySelector('.loading-gate-card').appendChild(btn);}}
window.addEventListener('beforeunload',()=>{state.disposed=true;for(const ch of state.channels)try{sb.removeChannel(ch)}catch(_){}});
document.addEventListener('DOMContentLoaded',boot,{once:true});
})();
