/* Tasneef Orders Final Stability v10023
   استخدم هذا الملف بدل tasneef_orders_shared_sync_v64.js وبدل tasneef_orders_stability_patch_v10022.js
*/
(function(){
  'use strict';
  if(window.__tasneefOrdersFinalStabilityV10023) return;
  window.__tasneefOrdersFinalStabilityV10023 = true;

  const SUPABASE_URL = 'https://zmjdqiswytxlbfgnfjfv.supabase.co';
  const SUPABASE_ANON_KEY = 'sb_publishable_ADsAC5MtBCusDgX62c8NaQ_LyyuTPeb';
  const STORE_KEY = 'tasneef_orders_v233';
  const FLOW_KEY = 'tasneef_orders_workflow_v8';
  const TABLE = 'orders_shared';
  const PAGE_SIZE = 12;
  let page = 1, pushing = false, loading = false, booted = false, saveTimer = null, lastLocalSnapshot = '';

  const $ = id => document.getElementById(id);
  const S = v => String(v ?? '').trim();
  const esc = v => S(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const num = v => { const n = Number(S(v).replace(/,/g,'').replace(/[^0-9.\-]/g,'')); return Number.isFinite(n) ? n : 0; };
  const money = v => num(v).toLocaleString('ar-SA',{minimumFractionDigits:2,maximumFractionDigits:2}) + ' ر.س';
  const seed = () => window.TASNEEF_ORDERS_SEED || {headers:[],orders:[]};
  const fallbackHeaders = ['رقم الطلب','رقم الطلب بالجروب','تاريخ الطلب','وقت الطلب','مرسل الطلب','المشروع','نوع العقار','رقم الشقة','اسم العميل','رقم العميل','المنفذ','التفاصيل','ملاحظات','تخص','تاريخ التنفيذ','كيفية التنفيذ','حالة التنفيذ','تقرير','السعر (شامل الضريبة)','الضريبة 15%','السعر قبل الضريبة','التكلفة','الربح','حالة السداد','رقم الفاتورة','فوترة بالسيستم'];
  const headers = () => (seed().headers || []).filter(h => S(h).indexOf('__excel_col_') !== 0);
  const H = i => headers()[i] || fallbackHeaders[i] || ('field_'+i);
  const field = (row, idx) => row ? (row[H(idx)] ?? row[fallbackHeaders[idx]] ?? '') : '';
  const normalizeNo = v => S(v).replace(/\s+/g,'').toUpperCase();
  const orderNoForRow = row => normalizeNo(row && (row[H(0)] || row[fallbackHeaders[0]] || row.order_no || row.orderNo || row['رقم الطلب / النظام'] || row['رقم النظام'] || row.id));
  const clone = obj => { try { return JSON.parse(JSON.stringify(obj || [])); } catch(_) { return []; } };

  function readRows(){ try{ const rows = JSON.parse(localStorage.getItem(STORE_KEY) || 'null'); if(Array.isArray(rows)) return rows; }catch(_){} return clone(seed().orders || []); }
  function readFlow(){ try{ const f = JSON.parse(localStorage.getItem(FLOW_KEY) || '{}'); return f && typeof f === 'object' ? f : {}; }catch(_){ return {}; } }
  function writeFlow(flow){ localStorage.setItem(FLOW_KEY, JSON.stringify(flow || {})); }
  function writeRows(rows, reason){ localStorage.setItem(STORE_KEY, JSON.stringify(rows || [])); lastLocalSnapshot = snapshot(rows || []); if(reason !== 'server-load') schedulePush('writeRows'); }
  function snapshot(rows){ return JSON.stringify((rows || []).map(r => [orderNoForRow(r), r.__tasneef_updated_at || '', field(r,18), field(r,23), field(r,13)])); }

  function normalizePayment(row){ const p = S(field(row,23) || row['حالة السداد'] || row['المالية'] || row.payment_status || row.finance_status); if(/آجل|أجل|اجل/i.test(p)) return 'آجل'; if(/تم\s*السداد|مسدد|مدفوع|تم\s*الدفع|سداد/i.test(p)) return 'تم السداد'; return p; }
  function normalizeConcern(row){ const c = S(field(row,13) || row['تخص'] || row.concern || row.belongs_to).replace(/\s+/g,' '); if(/عميل|العميل/i.test(c)) return 'client'; if(/جمعية|الجمعية|جميعة|الجميعة|اتحاد/i.test(c)) return 'association'; return ''; }
  function concernText(row){ const c = normalizeConcern(row); if(c==='client') return 'تخص العميل'; if(c==='association') return 'تخص الجمعية'; return S(field(row,13) || row['تخص'] || '-'); }
  function dateKey(row){ const raw=S(field(row,2)||row.created_at||row.updated_at||row.__tasneef_updated_at); let m=raw.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/); if(m) return `${m[3]}-${String(m[2]).padStart(2,'0')}-${String(m[1]).padStart(2,'0')}`; m=raw.match(/^(\d{4})[\/-](\d{1,2})[\/-](\d{1,2})/); if(m) return `${m[1]}-${String(m[2]).padStart(2,'0')}-${String(m[3]).padStart(2,'0')}`; return ''; }
  function orderNumberValue(row){ const no=orderNoForRow(row); const m=no.match(/(\d+)/g); return m&&m.length ? Number(m[m.length-1])||0 : 0; }
  function sortRows(rows){ return (rows||[]).slice().sort((a,b)=>{ const ua=S(a.__tasneef_updated_at||a.updated_at||a.modified_at||a.__server_updated_at); const ub=S(b.__tasneef_updated_at||b.updated_at||b.modified_at||b.__server_updated_at); if(ua||ub){ const c=ub.localeCompare(ua); if(c) return c; } const na=orderNumberValue(a), nb=orderNumberValue(b); if(nb!==na) return nb-na; return dateKey(b).localeCompare(dateKey(a)); }); }
  function normalizeRowForServer(row, stamp){ const r=Object.assign({}, row||{}); const no=orderNoForRow(r); if(no){ r.order_no=no; r.orderNo=no; if(!S(r[H(0)])) r[H(0)]=no; if(!S(r[fallbackHeaders[0]])) r[fallbackHeaders[0]]=no; } const pay=normalizePayment(r); if(pay) r[H(23)]=pay; const c=normalizeConcern(r); if(c==='client') r[H(13)]='تخص العميل'; if(c==='association') r[H(13)]='تخص الجمعية'; if(stamp) r.__tasneef_updated_at=stamp; return r; }

  async function rest(path, options){ const headers={apikey:SUPABASE_ANON_KEY, Authorization:'Bearer '+SUPABASE_ANON_KEY, Accept:'application/json', 'Content-Type':'application/json', Prefer:'resolution=merge-duplicates,return=minimal'}; return fetch(SUPABASE_URL+path, Object.assign({cache:'no-store', headers}, options||{})); }
  async function pushRows(reason, onlyOrderNo){ if(pushing || loading) return false; pushing=true; try{ const now=new Date().toISOString(); let rows=readRows().map(r=>normalizeRowForServer(r, (onlyOrderNo&&orderNoForRow(r)===onlyOrderNo)?now:(r.__tasneef_updated_at||''))); rows=sortRows(rows); localStorage.setItem(STORE_KEY, JSON.stringify(rows)); const flow=readFlow(); const payload=rows.filter(row=>!onlyOrderNo||orderNoForRow(row)===onlyOrderNo).map(row=>{ const no=orderNoForRow(row); if(!no) return null; return {order_no:no,data:normalizeRowForServer(row,row.__tasneef_updated_at||now),flow:flow[no]||{},updated_at:row.__tasneef_updated_at||now,updated_by:'orders_final_stability_v10023_'+(reason||'save')}; }).filter(Boolean); if(payload.length){ const res=await rest('/rest/v1/'+TABLE+'?on_conflict=order_no',{method:'POST',body:JSON.stringify(payload)}); if(!res.ok){ console.error('orders upsert failed',res.status,await res.text().catch(()=>'')); alert('لم يتم حفظ الأوردر في السيرفر. لا تعمل تحديث قبل تصوير الخطأ من Console.'); return false; } } await rest('/rest/v1/app_local_store?on_conflict=key',{method:'POST',body:JSON.stringify({key:STORE_KEY,value_text:JSON.stringify(rows),updated_at:new Date().toISOString(),updated_by:'orders_final_stability_v10023_cache'})}).catch(()=>{}); lastLocalSnapshot=snapshot(rows); return true; }catch(e){ console.error('pushRows v10023 failed',e); return false; }finally{ pushing=false; } }
  function schedulePush(reason){ clearTimeout(saveTimer); saveTimer=setTimeout(()=>pushRows(reason||'auto'),700); }
  async function loadServer(force){ if(loading || pushing) return false; loading=true; try{ const res=await rest('/rest/v1/'+TABLE+'?select=order_no,data,flow,updated_at&order=updated_at.desc&limit=10000',{method:'GET'}); if(!res.ok){ console.warn('orders load failed',res.status,await res.text().catch(()=>'')); return false; } const remote=await res.json(); const localMap=new Map(); readRows().forEach(r=>{const no=orderNoForRow(r); if(no) localMap.set(no,r);}); const map=new Map(), flow={}; (Array.isArray(remote)?remote:[]).forEach(rec=>{ const serverRow=normalizeRowForServer(rec.data||{}); const no=normalizeNo(rec.order_no||orderNoForRow(serverRow)); if(!no) return; serverRow.__server_updated_at=rec.updated_at||''; const local=localMap.get(no); const localTime=S(local&&local.__tasneef_updated_at); const serverTime=S(rec.updated_at); if(local&&localTime&&(!serverTime||localTime>serverTime)) map.set(no,normalizeRowForServer(local)); else map.set(no,serverRow); flow[no]=rec.flow||{}; }); localMap.forEach((row,no)=>{ if(!map.has(no)) map.set(no,normalizeRowForServer(row,row.__tasneef_updated_at||new Date().toISOString())); }); const rows=sortRows(Array.from(map.values())); localStorage.setItem(STORE_KEY,JSON.stringify(rows)); writeFlow(flow); lastLocalSnapshot=snapshot(rows); renderOrders(); return true; }catch(e){ console.warn('loadServer v10023 failed',e); return false; }finally{ loading=false; } }

  function ensureConcernFilter(){ if($('orderConcernFilterV10023')) return; const filters=document.querySelector('#orders .orders-filters-v233')||document.querySelector('#orders .filters'); if(!filters) return; const select=document.createElement('select'); select.id='orderConcernFilterV10023'; select.innerHTML='<option value="">كل: تخص العميل / الجمعية</option><option value="client">تخص العميل</option><option value="association">تخص الجمعية</option>'; select.onchange=()=>{page=1;renderOrders();}; const resetBtn=Array.from(filters.querySelectorAll('button')).find(b=>/إعادة/.test(S(b.textContent))); if(resetBtn) filters.insertBefore(select,resetBtn); else filters.appendChild(select); }
  function passFilters(row){ const q=S($('orderSearchV233')&&$('orderSearchV233').value).toLowerCase(); const project=S($('orderProjectFilterV233')&&$('orderProjectFilterV233').value); const exec=S($('orderExecutorFilterV233')&&$('orderExecutorFilterV233').value); const sender=S($('orderSenderFilterV233')&&$('orderSenderFilterV233').value); const status=S($('orderStatusFilterV233')&&$('orderStatusFilterV233').value); const pay=S($('orderPaymentFilterV233')&&$('orderPaymentFilterV233').value); const bill=S($('orderBillingFilterV233')&&$('orderBillingFilterV233').value); const concern=S($('orderConcernFilterV10023')&&$('orderConcernFilterV10023').value); const from=S($('orderFromDateV233')&&$('orderFromDateV233').value); const to=S($('orderToDateV233')&&$('orderToDateV233').value); if(project&&S(field(row,5))!==project) return false; if(exec&&S(field(row,10))!==exec) return false; if(sender&&S(field(row,4))!==sender) return false; if(status&&S(field(row,16))!==status) return false; if(pay){ const p=normalizePayment(row); if(/آجل|أجل|اجل/.test(pay)){ if(p!=='آجل') return false; } else if(/تم\s*السداد|مسدد|مدفوع|سداد/.test(pay)){ if(p!=='تم السداد') return false; } else if(S(field(row,23))!==pay&&p!==pay) return false; } if(bill&&S(field(row,25))!==bill) return false; if(concern&&normalizeConcern(row)!==concern) return false; const d=dateKey(row); if(from&&d&&d<from) return false; if(to&&d&&d>to) return false; if(q){ const hay=[field(row,0),field(row,1),field(row,4),field(row,5),field(row,8),field(row,9),field(row,10),field(row,11),field(row,13),field(row,16),field(row,23),field(row,24)].map(S).join(' ').toLowerCase(); if(!hay.includes(q)) return false; } return true; }
  function ensureStyle(){ if($('ordersFinalStyleV10023')) return; const st=document.createElement('style'); st.id='ordersFinalStyleV10023'; st.textContent='.orders-cards-v10023{display:grid;grid-template-columns:repeat(auto-fill,minmax(315px,1fr));gap:12px;margin-top:12px}.order-card-v10023{background:#fff;border:1px solid var(--line,#dce6e2);border-radius:18px;padding:14px;box-shadow:0 8px 22px rgba(10,64,51,.06);display:grid;gap:10px}.order-card-v10023.done{border-inline-start:5px solid #137a4b}.order-card-v10023.due{border-inline-start:5px solid #9a6b00}.order-card-v10023.cancel{border-inline-start:5px solid #b83232}.order-card-head-v10023{display:flex;justify-content:space-between;gap:10px}.order-chip-row-v10023{display:flex;gap:6px;flex-wrap:wrap}.order-chip-row-v10023 b,.order-card-head-v10023 span{border-radius:999px;padding:5px 9px;font-size:12px;background:#eef6f3;color:var(--brand,#0A4033);border:1px solid #d8e8e2}.order-chip-row-v10023 .finance{background:#fff5da;color:#8a6700}.order-chip-row-v10023 .bad{background:#fde8e8;color:#9d2222}.order-meta-v10023{display:grid;grid-template-columns:1fr 1fr;gap:7px}.order-meta-v10023 div{background:#f8fbfa;border:1px solid #edf1ef;border-radius:12px;padding:8px}.order-meta-v10023 small{display:block;color:#60706a;font-size:11px}.order-details-v10023{line-height:1.7;background:#fbfdfc;border:1px dashed #d8e8e2;border-radius:12px;padding:9px;min-height:64px;margin:0}.order-actions-v10023{display:flex;gap:7px;flex-wrap:wrap}.orders-pager-v10023{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-top:12px;background:#f8fbfa;border:1px solid var(--line,#dce6e2);border-radius:14px;padding:10px}#orderConcernFilterV10023{min-width:175px}'; document.head.appendChild(st); }
  function cardClass(row){ const st=S(field(row,16)), p=normalizePayment(row); if(/لم ينفذ|ملغي|إلغاء|الغاء/i.test(st)) return 'cancel'; if(p==='آجل'||/جزئي/i.test(p)) return 'due'; if(/تم التنفيذ/i.test(st)) return 'done'; return ''; }
  function card(row, originalIndex){ const cls=cardClass(row); return '<article class="order-card-v10023 '+cls+'"><div class="order-card-head-v10023"><div><h3>'+esc(field(row,0)||'-')+'</h3><small>رقم القروب: '+esc(field(row,1)||'-')+' | '+esc(field(row,2)||'-')+'</small></div><span>'+esc(field(row,5)||'-')+'</span></div><div class="order-chip-row-v10023"><b class="'+(cls==='cancel'?'bad':'')+'">التشغيل: '+esc(field(row,16)||'-')+'</b><b class="'+(cls==='due'?'finance':'')+'">السداد: '+esc(normalizePayment(row)||'-')+'</b><b>تخص: '+esc(concernText(row)||'-')+'</b></div><div class="order-meta-v10023"><div><small>العميل</small><strong>'+esc(field(row,8)||'-')+'</strong></div><div><small>الجوال</small><strong>'+esc(field(row,9)||'-')+'</strong></div><div><small>المنفذ</small><strong>'+esc(field(row,10)||'-')+'</strong></div><div><small>السعر شامل الضريبة</small><strong>'+esc(field(row,18)!==''?money(field(row,18)):'-')+'</strong></div></div><p class="order-details-v10023">'+(esc(S(field(row,11)).slice(0,180))||'لا توجد تفاصيل')+'</p><div class="order-actions-v10023"><button class="light" onclick="showOrderDetailsV6('+originalIndex+')">عرض</button><button onclick="editOrderV233('+originalIndex+')">تعديل</button><button class="light" onclick="sendOrderWhatsappV233('+originalIndex+')">واتساب</button><button class="danger" onclick="deleteOrderV233('+originalIndex+')">حذف</button></div></article>'; }
  function renderSummary(rows){ const done=rows.filter(r=>/تم التنفيذ/i.test(S(field(r,16)))).length; const dueRows=rows.filter(r=>normalizePayment(r)==='آجل'||/جزئي/i.test(normalizePayment(r))||(!normalizePayment(r)&&num(field(r,18))>0)); const paidRows=rows.filter(r=>normalizePayment(r)==='تم السداد'); const notDone=rows.filter(r=>/لم ينفذ|ملغي|إلغاء|الغاء/i.test(S(field(r,16)))).length; const revenue=rows.reduce((a,r)=>a+num(field(r,18)),0), vat=rows.reduce((a,r)=>a+num(field(r,19)),0), cost=rows.reduce((a,r)=>a+num(field(r,21)),0), profit=rows.reduce((a,r)=>a+num(field(r,22)),0); const dueTotal=dueRows.reduce((a,r)=>a+num(field(r,18)),0), paidTotal=paidRows.reduce((a,r)=>a+num(field(r,18)),0); if($('ordersTotalKpiV233')) $('ordersTotalKpiV233').textContent=rows.length; if($('ordersDoneKpiV233')) $('ordersDoneKpiV233').textContent=done; if($('ordersDueKpiV233')) $('ordersDueKpiV233').textContent=dueRows.length; if($('ordersProfitKpiV233')) $('ordersProfitKpiV233').textContent=money(profit).replace(' ر.س',''); if($('ordersSummaryV233')) $('ordersSummaryV233').innerHTML=[['إجمالي الإيرادات شامل الضريبة',money(revenue)],['إجمالي الضريبة 15%',money(vat)],['إجمالي التكلفة',money(cost)],['صافي الربح',money(profit)],['تم السداد',paidRows.length+' أوردر - '+money(paidTotal)],['آجل / غير مسدد',dueRows.length+' أوردر - '+money(dueTotal)],['لم ينفذ / ملغي',notDone+' أوردر']].map(x=>'<div class="summary-item"><b>'+esc(x[0])+'</b><br>'+esc(x[1])+'</div>').join(''); }
  function renderOrders(){ ensureStyle(); ensureConcernFilter(); const oldTable=$('ordersBodyV233'); if(oldTable&&oldTable.closest('.table-wrap')) oldTable.closest('.table-wrap').style.display='none'; let host=$('ordersCardsV10023')||$('ordersCardsV360')||$('ordersCardsV6'); if(!host){ const listCard=document.querySelector('.orders-list-card-v233')||$('orders'); if(!listCard) return; host=document.createElement('div'); host.id='ordersCardsV10023'; listCard.appendChild(host); } host.className='orders-cards-v10023'; let pager=$('ordersPagerV10023')||$('ordersPagerV360')||$('ordersPagerV6'); if(!pager){ pager=document.createElement('div'); pager.id='ordersPagerV10023'; host.after(pager); } pager.className='orders-pager-v10023'; const all=readRows(); const sorted=sortRows(all).map(r=>({r,i:all.findIndex(x=>orderNoForRow(x)===orderNoForRow(r))})); const filtered=sorted.filter(x=>passFilters(x.r)); const maxPage=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE)); page=Math.min(Math.max(1,page),maxPage); const slice=filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE); host.innerHTML=slice.map(x=>card(x.r,x.i)).join('')||'<div class="orders-empty-v6">لا توجد أوردرات حسب الفلتر الحالي</div>'; pager.innerHTML='<button class="light" '+(page<=1?'disabled':'')+' onclick="changeOrdersPageV6(-1)">السابق</button><b>صفحة '+page+' من '+maxPage+' — النتائج '+filtered.length+'</b><button class="light" '+(page>=maxPage?'disabled':'')+' onclick="changeOrdersPageV6(1)">التالي</button>'; renderSummary(filtered.map(x=>x.r)); }
  window.renderOrdersV233=renderOrders; window.changeOrdersPageV6=delta=>{page=Math.max(1,page+Number(delta||0)); renderOrders();}; window.renderOrdersFirstPageV6=()=>{page=1;renderOrders();};
  function markChangedRow(){ const rows=readRows(); const now=new Date().toISOString(); const editIndex=Number(S($('orderEditIndexV233')&&$('orderEditIndexV233').value)); let changedNo=''; if(Number.isFinite(editIndex)&&editIndex>=0&&rows[editIndex]){ rows[editIndex].__tasneef_updated_at=now; changedNo=orderNoForRow(rows[editIndex]); }else{ rows.forEach(r=>{ if(orderNoForRow(r)&&!r.__tasneef_updated_at) r.__tasneef_updated_at=now; }); if(rows[0]) changedNo=orderNoForRow(rows[0]); } localStorage.setItem(STORE_KEY,JSON.stringify(sortRows(rows))); return changedNo; }
  function wrapSave(){ ['saveOrderV233','ordersWorkflowCreateV8','ordersWorkflowInvoiceV8','ordersWorkflowApproveV8'].forEach(name=>{ const old=window[name]; if(typeof old!=='function'||old.__ordersFinalV10023) return; const wrapped=function(){ const ret=old.apply(this,arguments); setTimeout(async()=>{ const changedNo=markChangedRow(); await pushRows(name,changedNo||''); renderOrders(); if(typeof window.msg==='function') window.msg('تم حفظ الأوردر في السيرفر'); },350); setTimeout(()=>pushRows(name+'_second_check'),1600); return ret; }; wrapped.__ordersFinalV10023=true; window[name]=wrapped; }); const delOld=window.deleteOrderV233; if(typeof delOld==='function'&&!delOld.__ordersFinalV10023){ const wd=function(){ const ret=delOld.apply(this,arguments); setTimeout(()=>pushRows('delete').then(renderOrders),500); return ret; }; wd.__ordersFinalV10023=true; window.deleteOrderV233=wd; } }
  function bindFilters(){ ['orderSearchV233','orderProjectFilterV233','orderExecutorFilterV233','orderSenderFilterV233','orderStatusFilterV233','orderPaymentFilterV233','orderBillingFilterV233','orderFromDateV233','orderToDateV233','orderConcernFilterV10023'].forEach(id=>{ const el=$(id); if(el&&!el.__ordersFinalV10023){ el.__ordersFinalV10023=true; el.addEventListener('input',()=>{page=1;renderOrders();}); el.addEventListener('change',()=>{page=1;renderOrders();}); } }); }
  setInterval(()=>{ const rows=readRows(); const snap=snapshot(rows); if(lastLocalSnapshot&&snap!==lastLocalSnapshot&&!loading&&!pushing){ rows.forEach(r=>{ if(orderNoForRow(r)&&!r.__tasneef_updated_at) r.__tasneef_updated_at=new Date().toISOString(); }); localStorage.setItem(STORE_KEY,JSON.stringify(sortRows(rows))); schedulePush('watcher'); } lastLocalSnapshot=snap; },1200);
  function boot(){ if(booted) return; booted=true; try{ window.__tasneefOrdersSharedSyncV64=true; }catch(_){} wrapSave(); ensureConcernFilter(); bindFilters(); loadServer(true).then(()=>{wrapSave();ensureConcernFilter();bindFilters();renderOrders();}); setTimeout(()=>{wrapSave();ensureConcernFilter();bindFilters();renderOrders();},1200); setInterval(()=>{wrapSave();ensureConcernFilter();bindFilters();if(!pushing)loadServer(false);},45000); }
  document.addEventListener('click',e=>{ const btn=e.target&&e.target.closest&&e.target.closest('button'); const txt=S(btn&&btn.textContent); if(txt==='تحديث'||txt==='تحديث البيانات'||txt==='النظام محدث') setTimeout(()=>loadServer(true),120); },true);
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',boot); else boot(); window.addEventListener('load',()=>setTimeout(boot,300)); window.tasneefOrdersFinalStabilityV10023={load:()=>loadServer(true),push:()=>pushRows('manual'),render:renderOrders};
})();
