import fs from 'node:fs';
import assert from 'node:assert/strict';
const app=fs.readFileSync('app.js','utf8');
const sql=fs.readFileSync('supabase_unified_workers_link_v10910.sql','utf8');
const attendance=fs.readFileSync('tasneef_supervisor_attendance_from_unified_v434.js','utf8');
const html=fs.readFileSync('supervisor.html','utf8');
assert(app.includes("sb.rpc('tasneef_get_unified_supervisor_workers_v10910'"),'V10910 RPC missing');
assert(app.includes("sourceTable:'employees_master_v386',linkTable:'worker_project_links_v386'"),'unified source metadata missing');
assert(app.includes('assignmentSupervisorId:S(identity.assignmentSupervisorId||identity.assignment_supervisor_id)'),'assignment supervisor identity missing');
assert(sql.includes('from public.employees_master_v386 e'),'employees master source missing');
assert(sql.includes('from public.worker_project_links_v386 l'),'unified links source missing');
assert(!sql.includes('from public.workers w'),'legacy workers source must not be used');
assert(!sql.includes('from public.monthly_distribution d'),'monthly_distribution must not be used');
assert(sql.includes("'source_table','employees_master_v386'"),'source table response missing');
assert(sql.includes("'link_table','worker_project_links_v386'"),'link table response missing');
assert(sql.includes("lower(coalesce(nullif(j->>'is_active',''),'false'))='true'"),'strict active condition missing');
assert(sql.includes("'foreign_supervisor_workers','[]'::jsonb"),'foreign workers must be structurally empty');
assert(attendance.includes("V10910 unified workers system direct link"),'attendance build missing');
assert(attendance.includes('النظام الموحد للعمال'),'attendance source label missing');
assert(html.includes('app.js?v=10910-unified-workers-direct-link'),'cache bust missing');
assert(html.includes('tasneef_supervisor_attendance_from_unified_v434.js?v=10910-unified-workers-direct-link'),'attendance cache bust missing');
const result={version:'V10910',tests:15,passed:15,masterSource:'employees_master_v386',linkSource:'worker_project_links_v386',legacySourcesDisabled:['workers','monthly_distribution'],rpc:'tasneef_get_unified_supervisor_workers_v10910'};
fs.writeFileSync('UNIFIED_WORKERS_LINK_STATIC_TEST_V10910.json',JSON.stringify(result,null,2));
console.log(JSON.stringify(result,null,2));
